project_id = "risuhucghwkigqararqy"

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-tournament-request]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.chatbot-help]
verify_jwt = false

[functions.send-qr-email]
verify_jwt = false

[functions.send-reservation-reminder]
verify_jwt = false